[project]
name = "blogtuner"
version = "0.13.5"
description = "Dead simple static blog generator using markdown files"
readme = "README.md"
authors = [{ name = "All Tuner Labs", email = "hey@alltuner.com" }]
requires-python = ">=3.12"
dependencies = [
    "babel>=2.17.0",
    "click>=8.1.8",
    "feedgen>=1.0.0",
    "gitpython>=3.1.45",
    "jinja2>=3.1.6",
    "llm>=0.27.1",
    "loguru>=0.7.3",
    "mdformat>=0.7.22",
    "mistune>=3.1.4",
    "pillow>=11.3.0",
    "pydantic>=2.11.10",
    "pygments>=2.19.2",
    "python-dateutil>=2.9.0.post0",
    "python-dotenv>=1.1.1",
    "python-frontmatter>=1.1.0",
    "python-slugify[unidecode]>=8.0.4",
    "requests>=2.32.5",
    "substack-api>=1.1.1",
    "toml>=0.10.2",
    "typer>=0.19.2",
    "types-jinja2>=2.11.9",
]
license = "MIT"
license-files = ["LICENSE"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Framework :: Pydantic",
    "Framework :: Pydantic :: 2",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: Information Technology",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Internet :: WWW/HTTP :: Site Management",
    "Topic :: Text Processing :: Markup :: HTML",
    "Topic :: Text Processing :: Markup :: Markdown",
    "Topic :: Utilities",
    "Typing :: Typed",
]

[project.urls]
Homepage = "https://github.com/alltuner/blogtuner"
Issues = "https://github.com/alltuner/blogtuner/issues"

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true

[build-system]
requires = ["uv_build>=0.8,<0.9"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "mypy>=1.18.2",
    "pre-commit>=4.3.0",
    "ruff>=0.13.3",
    "types-pillow>=10.2.0.20240822",
    "types-pygments>=2.19.0.20250809",
    "types-python-dateutil>=2.9.0.20250822",
    "types-requests>=2.32.4.20250913",
    "types-toml>=0.10.8.20240310",
]

[project.scripts]
blogtuner = "blogtuner.cli:app"

[tool.ruff.lint]
extend-select = [
    # E and F are enabled by default
    'B',      # flake8-bugbear
    'C4',     # flake8-comprehensions
    'C90',    # mccabe
    'I',      # isort
    'N',      # pep8-naming
    'Q',      # flake8-quotes
    'RUF100', # ruff (unused noqa)
    'S',      # flake8-bandit
    'W',      # pycodestyle
]

[tool.ruff.lint.isort]
combine-as-imports = true
lines-after-imports = 2

[tool.mypy]
plugins = ['pydantic.mypy']
